### ISSUE TITLE
Can't install, need fix {arch}

### ISSUE THREAD

**Issue by Serrenima** [dashevo/dashcore-node#21]
Hi all,
```
mkdir: cannot create directory ‘/root’: Permission denied
npm ERR! code ELIFECYCLE
npm ERR! errno 1
...
```

Thanks.

**Comment by snogcel** [comment]
I spoke with @Skrutch via Discord and through conversation we decided the best way through was to reinstall his OS to use x86_64 system architecture. Though we could add this architecture into bitcore-node-dash it would require publishing to NPM, and due to the fact we're going to be removing the install script altogether in the near future, we decided this was the best way to proceed for now.

OK to close -- or we can keep open until download script is dropped.

**Comment by nmarley** [comment]
As snogcel stated, we're removing the download entirely and making it a separate dependency.

This work should be done by early next week at the latest, or you can use the  `develop` branch of this repo: https://github.com/dashevo/dashcore-node.
